var namespacerotor_1_1payload =
[
    [ "commit_unsubscription_t", "structrotor_1_1payload_1_1commit__unsubscription__t.html", "structrotor_1_1payload_1_1commit__unsubscription__t" ],
    [ "create_actor_t", "structrotor_1_1payload_1_1create__actor__t.html", "structrotor_1_1payload_1_1create__actor__t" ],
    [ "deregistration_notify_t", "structrotor_1_1payload_1_1deregistration__notify__t.html", "structrotor_1_1payload_1_1deregistration__notify__t" ],
    [ "deregistration_service_t", "structrotor_1_1payload_1_1deregistration__service__t.html", "structrotor_1_1payload_1_1deregistration__service__t" ],
    [ "discovery_cancel_t", "structrotor_1_1payload_1_1discovery__cancel__t.html", "structrotor_1_1payload_1_1discovery__cancel__t" ],
    [ "discovery_future_t", "structrotor_1_1payload_1_1discovery__future__t.html", "structrotor_1_1payload_1_1discovery__future__t" ],
    [ "discovery_promise_t", "structrotor_1_1payload_1_1discovery__promise__t.html", "structrotor_1_1payload_1_1discovery__promise__t" ],
    [ "discovery_reply_t", "structrotor_1_1payload_1_1discovery__reply__t.html", "structrotor_1_1payload_1_1discovery__reply__t" ],
    [ "discovery_request_t", "structrotor_1_1payload_1_1discovery__request__t.html", "structrotor_1_1payload_1_1discovery__request__t" ],
    [ "external_subscription_t", "structrotor_1_1payload_1_1external__subscription__t.html", "structrotor_1_1payload_1_1external__subscription__t" ],
    [ "external_unsubscription_t", "structrotor_1_1payload_1_1external__unsubscription__t.html", "structrotor_1_1payload_1_1external__unsubscription__t" ],
    [ "handler_call_t", "structrotor_1_1payload_1_1handler__call__t.html", "structrotor_1_1payload_1_1handler__call__t" ],
    [ "initialize_actor_t", "structrotor_1_1payload_1_1initialize__actor__t.html", "structrotor_1_1payload_1_1initialize__actor__t" ],
    [ "initialize_confirmation_t", "structrotor_1_1payload_1_1initialize__confirmation__t.html", null ],
    [ "link_request_t", "structrotor_1_1payload_1_1link__request__t.html", "structrotor_1_1payload_1_1link__request__t" ],
    [ "link_response_t", "structrotor_1_1payload_1_1link__response__t.html", null ],
    [ "registration_request_t", "structrotor_1_1payload_1_1registration__request__t.html", "structrotor_1_1payload_1_1registration__request__t" ],
    [ "registration_response_t", "structrotor_1_1payload_1_1registration__response__t.html", null ],
    [ "shutdown_confirmation_t", "structrotor_1_1payload_1_1shutdown__confirmation__t.html", null ],
    [ "shutdown_request_t", "structrotor_1_1payload_1_1shutdown__request__t.html", "structrotor_1_1payload_1_1shutdown__request__t" ],
    [ "shutdown_trigger_t", "structrotor_1_1payload_1_1shutdown__trigger__t.html", "structrotor_1_1payload_1_1shutdown__trigger__t" ],
    [ "start_actor_t", "structrotor_1_1payload_1_1start__actor__t.html", null ],
    [ "state_request_t", "structrotor_1_1payload_1_1state__request__t.html", "structrotor_1_1payload_1_1state__request__t" ],
    [ "state_response_t", "structrotor_1_1payload_1_1state__response__t.html", "structrotor_1_1payload_1_1state__response__t" ],
    [ "subscription_confirmation_t", "structrotor_1_1payload_1_1subscription__confirmation__t.html", "structrotor_1_1payload_1_1subscription__confirmation__t" ],
    [ "unlink_notify_t", "structrotor_1_1payload_1_1unlink__notify__t.html", "structrotor_1_1payload_1_1unlink__notify__t" ],
    [ "unlink_request_t", "structrotor_1_1payload_1_1unlink__request__t.html", "structrotor_1_1payload_1_1unlink__request__t" ],
    [ "unsubscription_confirmation_t", "structrotor_1_1payload_1_1unsubscription__confirmation__t.html", "structrotor_1_1payload_1_1unsubscription__confirmation__t" ]
];