var namespacerotor =
[
    [ "asio", "namespacerotor_1_1asio.html", "namespacerotor_1_1asio" ],
    [ "details", null, [
      [ "error_code_category", "classrotor_1_1details_1_1error__code__category.html", null ],
      [ "is_braces_constructible", "structrotor_1_1details_1_1is__braces__constructible.html", null ],
      [ "is_constructible", "structrotor_1_1details_1_1is__constructible.html", null ],
      [ "is_constructible< T, Arg >", "structrotor_1_1details_1_1is__constructible_3_01T_00_01Arg_01_4.html", null ],
      [ "is_constructible< T, void >", "structrotor_1_1details_1_1is__constructible_3_01T_00_01void_01_4.html", null ],
      [ "is_constructible< T, void, Arg >", "structrotor_1_1details_1_1is__constructible_3_01T_00_01void_00_01Arg_01_4.html", null ],
      [ "is_constructible< T, void, Args... >", "structrotor_1_1details_1_1is__constructible_3_01T_00_01void_00_01Args_8_8_8_01_4.html", null ],
      [ "size_of_t", "structrotor_1_1details_1_1size__of__t.html", null ],
      [ "size_of_t< T >", "structrotor_1_1details_1_1size__of__t_3_01T_01_4.html", null ],
      [ "size_of_t< T, Ts... >", "structrotor_1_1details_1_1size__of__t_3_01T_00_01Ts_8_8_8_01_4.html", null ]
    ] ],
    [ "ev", "namespacerotor_1_1ev.html", "namespacerotor_1_1ev" ],
    [ "payload", "namespacerotor_1_1payload.html", "namespacerotor_1_1payload" ],
    [ "plugin", null, [
      [ "address_maker_plugin_t", "structrotor_1_1plugin_1_1address__maker__plugin__t.html", "structrotor_1_1plugin_1_1address__maker__plugin__t" ],
      [ "child_manager_plugin_t", "structrotor_1_1plugin_1_1child__manager__plugin__t.html", "structrotor_1_1plugin_1_1child__manager__plugin__t" ],
      [ "delivery_plugin_base_t", "structrotor_1_1plugin_1_1delivery__plugin__base__t.html", "structrotor_1_1plugin_1_1delivery__plugin__base__t" ],
      [ "delivery_plugin_t", "structrotor_1_1plugin_1_1delivery__plugin__t.html", "structrotor_1_1plugin_1_1delivery__plugin__t" ],
      [ "foreigners_support_plugin_t", "structrotor_1_1plugin_1_1foreigners__support__plugin__t.html", "structrotor_1_1plugin_1_1foreigners__support__plugin__t" ],
      [ "init_shutdown_plugin_t", "structrotor_1_1plugin_1_1init__shutdown__plugin__t.html", "structrotor_1_1plugin_1_1init__shutdown__plugin__t" ],
      [ "inspected_local_delivery_t", "structrotor_1_1plugin_1_1inspected__local__delivery__t.html", null ],
      [ "lifetime_plugin_t", "structrotor_1_1plugin_1_1lifetime__plugin__t.html", "structrotor_1_1plugin_1_1lifetime__plugin__t" ],
      [ "link_client_plugin_t", "structrotor_1_1plugin_1_1link__client__plugin__t.html", "structrotor_1_1plugin_1_1link__client__plugin__t" ],
      [ "link_server_plugin_t", "structrotor_1_1plugin_1_1link__server__plugin__t.html", "structrotor_1_1plugin_1_1link__server__plugin__t" ],
      [ "local_delivery_t", "structrotor_1_1plugin_1_1local__delivery__t.html", null ],
      [ "locality_plugin_t", "structrotor_1_1plugin_1_1locality__plugin__t.html", "structrotor_1_1plugin_1_1locality__plugin__t" ],
      [ "plugin_base_t", "structrotor_1_1plugin_1_1plugin__base__t.html", "structrotor_1_1plugin_1_1plugin__base__t" ],
      [ "registry_plugin_t", "structrotor_1_1plugin_1_1registry__plugin__t.html", "structrotor_1_1plugin_1_1registry__plugin__t" ],
      [ "resources_plugin_t", "structrotor_1_1plugin_1_1resources__plugin__t.html", "structrotor_1_1plugin_1_1resources__plugin__t" ],
      [ "starter_plugin_t", "structrotor_1_1plugin_1_1starter__plugin__t.html", "structrotor_1_1plugin_1_1starter__plugin__t" ]
    ] ],
    [ "wx", "namespacerotor_1_1wx.html", "namespacerotor_1_1wx" ],
    [ "actor_base_t", "structrotor_1_1actor__base__t.html", "structrotor_1_1actor__base__t" ],
    [ "actor_config_builder_t", "structrotor_1_1actor__config__builder__t.html", "structrotor_1_1actor__config__builder__t" ],
    [ "actor_config_t", "structrotor_1_1actor__config__t.html", "structrotor_1_1actor__config__t" ],
    [ "address_mapping_t", "structrotor_1_1address__mapping__t.html", "structrotor_1_1address__mapping__t" ],
    [ "address_t", "structrotor_1_1address__t.html", "structrotor_1_1address__t" ],
    [ "handler_base_t", "structrotor_1_1handler__base__t.html", "structrotor_1_1handler__base__t" ],
    [ "handler_t", "structrotor_1_1handler__t.html", null ],
    [ "handler_t< Handler, std::enable_if_t< details::is_actor_handler_v< Handler > > >", "structrotor_1_1handler__t_3_01Handler_00_01std_1_1enable__if__t_3_01details_1_1is__actor__handler__v_3_01Handler_01_4_01_4_01_4.html", "structrotor_1_1handler__t_3_01Handler_00_01std_1_1enable__if__t_3_01details_1_1is__actor__handler__v_3_01Handler_01_4_01_4_01_4" ],
    [ "handler_t< Handler, std::enable_if_t< details::is_plugin_handler_v< Handler > > >", "structrotor_1_1handler__t_3_01Handler_00_01std_1_1enable__if__t_3_01details_1_1is__plugin__handl20483f260024489c47703352b58225ce.html", "structrotor_1_1handler__t_3_01Handler_00_01std_1_1enable__if__t_3_01details_1_1is__plugin__handl20483f260024489c47703352b58225ce" ],
    [ "handler_t< lambda_holder_t< Handler, M >, std::enable_if_t< details::is_lambda_handler_v< lambda_holder_t< Handler, M > > > >", "structrotor_1_1handler__t_3_01lambda__holder__t_3_01Handler_00_01M_01_4_00_01std_1_1enable__if__9f0d4eb8f11444e50079417975696fb3.html", "structrotor_1_1handler__t_3_01lambda__holder__t_3_01Handler_00_01M_01_4_00_01std_1_1enable__if__9f0d4eb8f11444e50079417975696fb3" ],
    [ "handler_traits", "structrotor_1_1handler__traits.html", null ],
    [ "handler_traits< lambda_holder_t< M, H > >", "structrotor_1_1handler__traits_3_01lambda__holder__t_3_01M_00_01H_01_4_01_4.html", null ],
    [ "handler_traits< void(A::*)(M &) noexcept >", "structrotor_1_1handler__traits_3_01void_07A_1_1_5_08_07M_01_6_08_01noexcept_01_4.html", "structrotor_1_1handler__traits_3_01void_07A_1_1_5_08_07M_01_6_08_01noexcept_01_4" ],
    [ "lambda_holder_t", "structrotor_1_1lambda__holder__t.html", "structrotor_1_1lambda__holder__t" ],
    [ "message_base_t", "structrotor_1_1message__base__t.html", "structrotor_1_1message__base__t" ],
    [ "message_t", "structrotor_1_1message__t.html", "structrotor_1_1message__t" ],
    [ "plugin_storage_base_t", "structrotor_1_1plugin__storage__base__t.html", "structrotor_1_1plugin__storage__base__t" ],
    [ "plugin_storage_t", "structrotor_1_1plugin__storage__t.html", "structrotor_1_1plugin__storage__t" ],
    [ "registry_t", "structrotor_1_1registry__t.html", "structrotor_1_1registry__t" ],
    [ "request_base_t", "structrotor_1_1request__base__t.html", "structrotor_1_1request__base__t" ],
    [ "request_builder_t", "structrotor_1_1request__builder__t.html", "structrotor_1_1request__builder__t" ],
    [ "request_curry_t", "structrotor_1_1request__curry__t.html", "structrotor_1_1request__curry__t" ],
    [ "request_traits_t", "structrotor_1_1request__traits__t.html", "structrotor_1_1request__traits__t" ],
    [ "request_unwrapper_t", "structrotor_1_1request__unwrapper__t.html", "structrotor_1_1request__unwrapper__t" ],
    [ "request_unwrapper_t< intrusive_ptr_t< T > >", "structrotor_1_1request__unwrapper__t_3_01intrusive__ptr__t_3_01T_01_4_01_4.html", "structrotor_1_1request__unwrapper__t_3_01intrusive__ptr__t_3_01T_01_4_01_4" ],
    [ "request_wrapper_t", "structrotor_1_1request__wrapper__t.html", "structrotor_1_1request__wrapper__t" ],
    [ "request_wrapper_t< T, std::enable_if_t< std::is_base_of_v< arc_base_t< T >, T > > >", "structrotor_1_1request__wrapper__t_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_e87ff55122062e5a77521960ca0ac849.html", "structrotor_1_1request__wrapper__t_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_e87ff55122062e5a77521960ca0ac849" ],
    [ "response_helper_t", "structrotor_1_1response__helper__t.html", "structrotor_1_1response__helper__t" ],
    [ "response_helper_t< intrusive_ptr_t< Responce > >", "structrotor_1_1response__helper__t_3_01intrusive__ptr__t_3_01Responce_01_4_01_4.html", "structrotor_1_1response__helper__t_3_01intrusive__ptr__t_3_01Responce_01_4_01_4" ],
    [ "subscription_container_t", "structrotor_1_1subscription__container__t.html", "structrotor_1_1subscription__container__t" ],
    [ "subscription_info_t", "structrotor_1_1subscription__info__t.html", "structrotor_1_1subscription__info__t" ],
    [ "subscription_point_t", "structrotor_1_1subscription__point__t.html", "structrotor_1_1subscription__point__t" ],
    [ "subscription_t", "structrotor_1_1subscription__t.html", "structrotor_1_1subscription__t" ],
    [ "supervisor_config_builder_t", "structrotor_1_1supervisor__config__builder__t.html", "structrotor_1_1supervisor__config__builder__t" ],
    [ "supervisor_config_t", "structrotor_1_1supervisor__config__t.html", "structrotor_1_1supervisor__config__t" ],
    [ "supervisor_t", "structrotor_1_1supervisor__t.html", "structrotor_1_1supervisor__t" ],
    [ "system_context_t", "structrotor_1_1system__context__t.html", "structrotor_1_1system__context__t" ],
    [ "wrapped_request_t", "structrotor_1_1wrapped__request__t.html", "structrotor_1_1wrapped__request__t" ],
    [ "wrapped_request_t< T, std::enable_if_t< std::is_base_of_v< arc_base_t< T >, T > > >", "structrotor_1_1wrapped__request__t_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_e8c9a041113eceda006cb13907d336c0.html", "structrotor_1_1wrapped__request__t_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_e8c9a041113eceda006cb13907d336c0" ],
    [ "wrapped_response_t", "structrotor_1_1wrapped__response__t.html", "structrotor_1_1wrapped__response__t" ]
];